[icons]
# font awesome
TelegramDesktop = ""
firefox = ""
Alacritty = ""
Termite = ""
Thunderbird = ""
Gpick = ""
Nautilus = "📘"
# smile emoji
MyNiceProgram = "😛"

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

[general]
separator = "  "
default_icon = ""
wm_property = "class"

[options]
remove_duplicates = false
use_instance = false
no_names = false
no_icon_names = false
